export type Language = {
  code: string;
  name: string;
  icon: string;
};

export const LANGUAGES: Record<string, Language> = {
  af: { code: 'af', name: 'Afrikaans', icon: 'af' },
  sq: { code: 'sq', name: 'Shqip', icon: 'sq' },
  am: { code: 'am', name: 'አማርኛ', icon: 'am' },
  ar: { code: 'ar', name: 'العربية', icon: 'ar' },
  hy: { code: 'hy', name: 'հայերեն', icon: 'hy' },
  as: { code: 'as', name: 'অসমীয়া', icon: 'as' },
  az: { code: 'az', name: 'Azərbaycan (Latın)', icon: 'az' },
  bn: { code: 'bn', name: 'বাংলা', icon: 'bn' },
  ba: { code: 'ba', name: 'Башҡорт теле', icon: 'ba' },
  eu: { code: 'eu', name: 'Euskara', icon: 'eu' },
  bho: { code: 'bho', name: 'भोजपुरी', icon: 'bh' },
  brx: { code: 'brx', name: 'बर’', icon: 'bx' },
  bs: { code: 'bs', name: 'Bosanski (Latinica)', icon: 'bs' },
  bg: { code: 'bg', name: 'Български', icon: 'bg' },
  yue: { code: 'yue', name: '廣東話', icon: 'yu' },
  ca: { code: 'ca', name: 'Català', icon: 'ca' },
  lzh: { code: 'lzh', name: '文言文', icon: 'lzh' },
  'zh-Hans': { code: 'zh-Hans', name: '简体中文', icon: 'zhs' },
  'zh-Hant': { code: 'zh-Hant', name: '繁體中文', icon: 'zht' },
  sn: { code: 'sn', name: 'chiShona', icon: 'sn' },
  hr: { code: 'hr', name: 'hrvatski', icon: 'hr' },
  cs: { code: 'cs', name: 'čeština', icon: 'cs' },
  da: { code: 'da', name: 'Dansk', icon: 'da' },
  prs: { code: 'prs', name: 'دری', icon: 'prs' },
  dv: { code: 'dv', name: 'ދިވެހި', icon: 'dv' },
  doi: { code: 'doi', name: 'डोगरी', icon: 'do' },
  nl: { code: 'nl', name: 'Nederlands', icon: 'nl' },
  en: { code: 'en', name: 'English', icon: 'en' },
  et: { code: 'et', name: 'Eesti', icon: 'et' },
  fo: { code: 'fo', name: 'Føroyskt', icon: 'fo' },
  fj: { code: 'fj', name: 'Vosa Vakaviti', icon: 'fj' },
  fil: { code: 'fil', name: 'Filipino', icon: 'fil' },
  fi: { code: 'fi', name: 'Suomi', icon: 'fi' },
  fr: { code: 'fr', name: 'Français', icon: 'fr' },
  'fr-ca': { code: 'fr-ca', name: 'Français (Canada)', icon: 'frC' },
  gl: { code: 'gl', name: 'Galego', icon: 'gl' },
  ka: { code: 'ka', name: 'ქართული', icon: 'ka' },
  de: { code: 'de', name: 'Deutsch', icon: 'de' },
  el: { code: 'el', name: 'Ελληνικά', icon: 'el' },
  gu: { code: 'gu', name: 'ગુજરાતી', icon: 'gu' },
  ht: { code: 'ht', name: 'Kreyòl Ayisyen', icon: 'ht' },
  ha: { code: 'ha', name: 'Hausa', icon: 'ha' },
  he: { code: 'he', name: 'עברית', icon: 'he' },
  hi: { code: 'hi', name: 'हिन्दी', icon: 'hi' },
  mww: { code: 'mww', name: 'Hmong Daw (Latin)', icon: 'mww' },
  hu: { code: 'hu', name: 'Magyar', icon: 'hu' },
  is: { code: 'is', name: 'Íslenska', icon: 'is' },
  ig: { code: 'ig', name: 'Igbo', icon: 'ig' },
  id: { code: 'id', name: 'Bahasa Indonesia', icon: 'id' },
  ikt: { code: 'ikt', name: 'Inuinnaqtun', icon: 'ikt' },
  iu: { code: 'iu', name: 'ᐃᓄᒃᑎᑐᑦ', icon: 'iu' },
  'iu-Latn': { code: 'iu-Latn', name: 'Inuktitut (Latiin)', icon: 'iuL' },
  ga: { code: 'ga', name: 'Gaeilge', icon: 'ga' },
  it: { code: 'it', name: 'Italiano', icon: 'it' },
  ja: { code: 'ja', name: '日本語', icon: 'ja' },
  kn: { code: 'kn', name: 'ಕನ್ನಡ', icon: 'kn' },
  ks: { code: 'ks', name: 'کٲشُر', icon: 'ks' },
  kk: { code: 'kk', name: 'Қазақ тілі', icon: 'kk' },
  km: { code: 'km', name: 'ខ្មែរ', icon: 'km' },
  rw: { code: 'rw', name: 'Ikinyarwanda', icon: 'rw' },
  'tlh-Latn': { code: 'tlh-Latn', name: 'Klingon', icon: 'tlL' },
  'tlh-Piqd': { code: 'tlh-Piqd', name: 'Klingon (pIqaD)', icon: 'tlP' },
  gom: { code: 'gom', name: 'कोंकणी', icon: 'gom' },
  ko: { code: 'ko', name: '한국어', icon: 'ko' },
  ku: { code: 'ku', name: 'کوردی (ناوەندی)', icon: 'ku' },
  kmr: { code: 'kmr', name: 'Kurdî (Bakurî)', icon: 'kmr' },
  ky: { code: 'ky', name: 'Кыргызча (Кирилица)', icon: 'ky' },
  lo: { code: 'lo', name: 'ລາວ', icon: 'lo' },
  lv: { code: 'lv', name: 'Latviešu', icon: 'lv' },
  lt: { code: 'lt', name: 'Lietuvių', icon: 'lt' },
  ln: { code: 'ln', name: 'Lingala', icon: 'ln' },
  dsb: { code: 'dsb', name: 'Dolnoserbšćina', icon: 'dsb' },
  lug: { code: 'lug', name: 'Luganda', icon: 'lug' },
  mk: { code: 'mk', name: 'Македонски', icon: 'mk' },
  mai: { code: 'mai', name: 'मैथिली', icon: 'mai' },
  mg: { code: 'mg', name: 'Malagasy', icon: 'mg' },
  ms: { code: 'ms', name: 'Bahasa Melayu (Latiin)', icon: 'ms' },
  ml: { code: 'ml', name: 'മലയാളം', icon: 'ml' },
  mt: { code: 'mt', name: 'Malti', icon: 'mt' },
  mi: { code: 'mi', name: 'Te Reo Māori', icon: 'mi' },
  mr: { code: 'mr', name: 'मराठी', icon: 'mr' },
  'mn-Cyrl': { code: 'mn-Cyrl', name: 'Монгол (Кирилл)', icon: 'mnC' },
  'mn-Mong': { code: 'mn-Mong', name: 'ᠮᠣᠩᠭᠣᠯ (ᠲᠣᠭᠠᠯᠢᠭ)', icon: 'mnM' },
  my: { code: 'my', name: 'မြန်မာ', icon: 'my' },
  ne: { code: 'ne', name: 'नेपाली', icon: 'ne' },
  nb: { code: 'nb', name: 'Norsk (Bokmål)', icon: 'nb' },
  nya: { code: 'nya', name: 'Nyanja', icon: 'nya' },
  or: { code: 'or', name: 'ଓଡ଼ିଆ', icon: 'or' },
  ps: { code: 'ps', name: 'پښتو', icon: 'ps' },
  fa: { code: 'fa', name: 'فارسی', icon: 'fa' },
  pl: { code: 'pl', name: 'Polski', icon: 'pl' },
  pt: { code: 'pt', name: 'Português (Brasil)', icon: 'pt' },
  'pt-pt': { code: 'pt-pt', name: 'Português (Portugal)', icon: 'ptP' },
  pa: { code: 'pa', name: 'ਪੰਜਾਬੀ', icon: 'pa' },
  otq: { code: 'otq', name: 'Hñąñho (Otomí de Querétaro)', icon: 'otq' },
  ro: { code: 'ro', name: 'Română', icon: 'ro' },
  run: { code: 'run', name: 'Ikirundi', icon: 'run' },
  ru: { code: 'ru', name: 'Русский', icon: 'ru' },
  sm: { code: 'sm', name: 'Gagana Sāmoa (Latiin)', icon: 'sm' },
  'sr-Cyrl': { code: 'sr-Cyrl', name: 'Српски (Ћирилица)', icon: 'srC' },
  'sr-Latn': { code: 'sr-Latn', name: 'Srpski (Latinica)', icon: 'srL' },
  st: { code: 'st', name: 'Sesotho', icon: 'st' },
  nso: { code: 'nso', name: 'Sesotho sa Leboa', icon: 'nso' },
  tn: { code: 'tn', name: 'Setswana', icon: 'tn' },
  sd: { code: 'sd', name: 'سنڌي', icon: 'sd' },
  si: { code: 'si', name: 'සිංහල', icon: 'si' },
  sk: { code: 'sk', name: 'Slovenčina', icon: 'sk' },
  sl: { code: 'sl', name: 'Slovenščina', icon: 'sl' },
  so: { code: 'so', name: 'Soomaali (Carabi)', icon: 'so' },
  es: { code: 'es', name: 'Español', icon: 'es' },
  sw: { code: 'sw', name: 'Kiswahili (Latiin)', icon: 'sw' },
  sv: { code: 'sv', name: 'Svenska', icon: 'sv' },
  ty: { code: 'ty', name: 'Reo Tahiti', icon: 'ty' },
  ta: { code: 'ta', name: 'தமிழ்', icon: 'ta' },
  tt: { code: 'tt', name: 'Татарча (Latiin)', icon: 'tt' },
  te: { code: 'te', name: 'తెలుగు', icon: 'te' },
  th: { code: 'th', name: 'ไทย', icon: 'th' },
  bo: { code: 'bo', name: 'བོད་སྐད', icon: 'bo' },
  ti: { code: 'ti', name: 'ትግርኛ', icon: 'ti' },
  to: { code: 'to', name: 'Lea Fakatonga', icon: 'to' },
  tr: { code: 'tr', name: 'Türkçe', icon: 'tr' },
  tk: { code: 'tk', name: 'Türkmençe (Latiin)', icon: 'tk' },
  uk: { code: 'uk', name: 'Українська', icon: 'uk' },
  hsb: { code: 'hsb', name: 'Hornjoserbšćina', icon: 'hsb' },
  ur: { code: 'ur', name: 'اردو', icon: 'ur' },
  ug: { code: 'ug', name: 'ئۇيغۇرچە (Carabi)', icon: 'ug' },
  uz: { code: 'uz', name: "O'zbekcha (Latiin)", icon: 'uz' },
  vi: { code: 'vi', name: 'Tiếng Việt', icon: 'vi' },
  cy: { code: 'cy', name: 'Cymraeg', icon: 'cy' },
  xh: { code: 'xh', name: 'isiXhosa', icon: 'xh' },
  yo: { code: 'yo', name: 'Yorùbá', icon: 'yo' },
  yua: { code: 'yua', name: 'Yucatec Maya', icon: 'yua' },
  zu: { code: 'zu', name: 'isiZulu', icon: 'zu' },
};
